name: Keep Workflows alive
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 0 1 * *'
jobs:
  workflow-keepalive:
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
    - name: keepalive
      uses: gneiss15/WorkflowKeepAliveByGhEnable@v1
