name: Test Releases
on:
  workflow_dispatch:
  push:
permissions:
  actions: write
  contents: write
defaults:
  run:
    shell: bash
env:
  GH_TOKEN: ${{ github.token }}
jobs:
  linux:
    runs-on: ubuntu-latest
    #timeout-minutes: 180
    #outputs:
    #  output1: ${{ steps.CheckSkips.outputs.skip }}
    #  output2: ${{ steps.CheckSkips.outputs.skip2 }}
    steps:
    - name: Set skip(s)
      id: CheckSkips
      run: |
        echo "skip=true" >> $GITHUB_OUTPUT
        echo "skip2=false" >> $GITHUB_OUTPUT

    - name: Show
      run: |
        echo steps.CheckSkips.outputs.skip: ${{ steps.CheckSkips.outputs.skip }}
        echo steps.CheckSkips.outputs.skip2: ${{ steps.CheckSkips.outputs.skip2 }}

    - name: Show if skip false
      #if: ${{ ! steps.CheckSkips.outputs.skip }}
      if: steps.CheckSkips.outputs.skip == 'false'
      run: |
        echo skip == false

    - name: Show if skip true
      #if: ${{ steps.CheckSkips.outputs.skip }}
      if: steps.CheckSkips.outputs.skip == 'true'
      run: |
        echo skip == true

    - name: Show if skip2 false
      #if: ${{ ! steps.CheckSkips.outputs.skip2 }}
      if: steps.CheckSkips.outputs.skip2 == 'false'
      run: |
        echo skip2 == false

    - name: Show if skip2 true
      #if: ${{ steps.CheckSkips.outputs.skip2 }}
      if: steps.CheckSkips.outputs.skip2 == 'true'
      run: |
        echo skip2 == true

